# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 802bf19f9ddf4e541e5b5cca5bc67aa36019bb7db8d943a21eb1a984443d4d5d4c9cc5814ed2d0d627054f884201b5f22d3d5006cf09f5b6db1799551db54ded

test:
  secret_key_base: 2b8609b2e76f2b12d5b2cc9bf1b8080c7ad94de53acd9161bac9a54c9ea310f1b046124067852b7c361374ed9a175333ef7958e1d82956d09ef10fcca6fa01f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
